provider:
  host: <server-host-name> #Aurora support to provide

client:
  client-id: <application-client-id> #Aurora support to provide
  client-secret: <application-client-secret> #Aurora support to provide
  post-logout-uri: http://localhost:8080/login
  scope: openid
  authorization-grant-type: authorization_code


spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name : Aurora
            client-id: <application-client-id> #Aurora support to provide
            client-secret: <application-client-secret> #Aurora support to provide
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          wso2:
            issuer-uri: <aurora issuer> #Aurora support to provide

  thymeleaf:
    cache: false
